version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - iot-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: iot-server
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - iot-network
    depends_on:
      - redis
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: iot-client
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - iot-network
    depends_on:
      - server
    restart: unless-stopped

networks:
  iot-network:
    driver: bridge

volumes:
  redis_data:
