version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./back-end/.env
    networks:
      - iot-network
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - ./front-end/.env
    networks:
      - iot-network
    depends_on:
      - backend
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - iot-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - iot-network
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

networks:
  iot-network:
    driver: bridge

volumes:
  redis_data:
