version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
    env_file:
      - ./back-end/.env
    volumes:
      - ./back-end:/app
      - /app/node_modules
    networks:
      - iot-network
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    env_file:
      - ./front-end/.env
    volumes:
      - ./front-end:/app
      - /app/node_modules
      - /app/.next
    networks:
      - iot-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  iot-network:
    driver: bridge

volumes:
  redis_data:
