services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - iot4-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: iot4-server
    ports:
      - "8004:8004"
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - iot4-network
    depends_on:
      - redis
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: iot4-client
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - iot4-network
    depends_on:
      - server
    restart: unless-stopped

networks:
  iot4-network:
    driver: bridge

volumes:
  redis_data: