version: '3.8'

services:
  iot4-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - iot-network
    restart: unless-stopped

  iot4-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - iot-network
    depends_on:
      - iot4-server
    restart: unless-stopped

networks:
  iot-network:
    driver: bridge
