version: '3.8'

services:
  iot3-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=development
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - iot-network
    depends_on:
      - iot3-redis
    restart: unless-stopped

  iot3-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development
    env_file:
      - ./client/.env
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - iot-network
    depends_on:
      - iot3-server
    restart: unless-stopped

  iot3-redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - iot-network
    restart: unless-stopped
    command: redis-server --appendonly yes

networks:
  iot-network:
    driver: bridge

volumes:
  redis_data: