version: '3.8'

services:
  iot5:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=production
      # - DATABASE_URL=postgresql://user:password@db:5432/mydb?schema=public
    env_file:
      - .env
    # depends_on:
    #   - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - app-network

  # db:
  #   image: postgres:15
  #   environment:
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_DB=mydb
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: